### ISSUE TITLE
Как использовать делегирование событий?

### ISSUE THREAD

**Issue by nimblemo** [philipshurpik/Framework7-MVC-base#1]
Здравствуйте, строю приложение по вашему шаблону, и столкнулся с небольшой проблемкой.

```
{
                element: '.chip-start',
		event: 'click',
		handler: startChip
    }
```
можно ли как то модели событий производить делегирование,  с целью определения обработчиков для несозданных в Dom элементах?

**Comment by philipshurpik** [comment]
привет )
сорри, я уже не помню - этот шаблон был написан несколько лет назад :)
но скорее всего это не предусматривалось - то есть надо написать какой-то свой код, что бы обработчики добавлялись при создании DOM элемента

**Comment by nimblemo** [comment]
Да действительно стоило самому разобраться.

```
	function bindEvents(bindings) {
		for (var i in bindings) {
			$(bindings[i].element).on(bindings[i].event, bindings[i].handler);
		}
	}
```
